name: Build Desktop Apps

on: push

jobs:
  # JOB 1: Build the Linux App on a Linux Server
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build React Code
        run: npm run build
        
      - name: Package Linux App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --linux -p never
        # Added '-p never' to stop it from trying to publish a Release for now.
        # It will just build the file and let us download it as an Artifact.
        
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-App
          path: dist/*.AppImage

  # JOB 2: Build the Windows App on a Windows Server
  build-win:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build React Code
        run: npm run build
        
      - name: Package Windows App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win -p never
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist/*.exe